name: Deploy - Production

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh/
          echo "$SSH_PRIVATE_KEY" > ./deploy.key
          sudo chmod 600 ./deploy.key
        shell: bash
        env:
          SSH_PRIVATE_KEY: ${{secrets.SSH_MACHINE_USER_PRIVATE_KEY}}
        
      - name: Adding Known Hosts
        run: echo "${{ secrets.SSH_HOST }}"
        
      - name: Adding Known Hosts
        run: ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to production
        run: ssh -i ./deploy.key www-data@${{ secrets.SSH_HOST }}  'sh /opt/apps/rncs-api-proxy/rncs-api-proxy-deploy.sh'
